name: worrrkspace
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  # --- Core ---
  - python=3.10.12
  - pip
  - numpy
  - pandas
  - polars
  - pyarrow
  - duckdb
  - orjson
  - xxhash

  # --- AI & Compute ---
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - faiss-gpu
  - libtorrent-rasterbar

  # --- UI & System ---
  - pyqt=6
  - qt-webengine
  - psutil
  - zeroconf

  # --- Build Tools ---
  - cmake
  - ninja
  - vswhere
  - vs2015_runtime

  - pip:
      # --- Networking & VPN ---
      - aioquic
      - wmi  # Управление Windows интерфейсами (для VPN)
      - pywin32  # WinAPI
      - cryptography
      - netifaces

      # --- Distributed Compute ---
      - ray[default]
      - lz4
      - accelerate
      # bitsandbytes на Windows требует специальной установки, 
      # но в requirements мы его оставим, pip попробует найти wheel, мало ли прокатит
      - bitsandbytes-windows  
      - onnxruntime-gpu

      # --- UI & Utils ---
      - qasync
      - NodeGraphQt
      - pytablericons
      - superqt
      - playwright
      - watchdog
      
      # --- Data & Viz ---
      - transformers
      - robyn
      - psqlpy
      - markdown
      - plotly
      - pyinstaller #playwright install chromium